### ISSUE TITLE
Can't add the library into my Android Studio Project

### ISSUE THREAD

**Issue by SevrainChea** [jOOQ/jOOU#9]
Hi,
I tried importing this library into my Android project, but when I try to run my app, I have the following error : 

FATAL EXCEPTION: main
                                                            Process: sevrain.test, PID: 6133
                                                            java.lang.NoClassDefFoundError: Failed resolution of: Lorg/joou/UByte;
                                                                at sevrain.test.Reglages.concatenateByteArray(Reglages.java:142)
                                                                at sevrain.test.MainActivity$4.onClick(MainActivity.java:123)
                                                                at android.view.View.performClick(View.java:5198)
                                                                at android.view.View$PerformClick.run(View.java:21147)
                                                                at android.os.Handler.handleCallback(Handler.java:739)
                                                                at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                at android.os.Looper.loop(Looper.java:148)
                                                                at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                             Caused by: java.lang.ClassNotFoundException: Didn't find class "org.joou.UByte" on path: DexPathList[[dex file "/data/data/sevrain.test/files/instant-run/dex/slice-support-annotations-23.3.0_5d2ef72a253a42531cccf688b31bc628a56ee084-classes.dex", dex file "/data/data/sevrain.test/files/instant-run/dex/slice-slice_9-classes.dex", dex file "/data/data/sevrain.test/files/instant-run/dex/slice-slice_8-classes.dex", dex file "/data/data/sevrain.test/files/instant-run/dex/slice-slice_7-classes.dex", dex file "/data/data/sevrain.test/files/instant-run/dex/slice-slice_6-classes.dex", dex file "/data/data/sevrain.test/files/instant-run/dex/slice-slice_5-classes.dex", dex file "/data/data/sevrain.test/files/instant-run/dex/slice-slice_4-classes.dex", dex file "/data/data/sevrain.test/files/instant-run/dex/slice-slice_3-classes.dex", dex file "/data/data/sevrain.test/files/instant-run/dex/slice-slice_2-classes.dex", dex file "/data/data/sevrain.test/files/instant-run/dex/slice-slice_1-classes.dex", dex file "/data/data/sevrain.test/files/instant-run/dex/slice-slice_0-classes.dex", dex file "/data/data/sevrain.test/files/instant-run/dex/slice-internal_impl-23.3.0_f0e052e442ee65b2a8a47f38f0f7af896de29339-classes.dex", dex file "/data/data/sevrain.test/files/instant-run/dex/slice-com.android.support-support-vector-drawable-23.3.0_010360adcd346090b0f9993e30fbd326f7ddc57e-classes.dex", dex file "/data/data/sevrain.test/files/instant-run/dex/slice-com.android.support-support-v4-23.3.0_0c2c65f8dc40f972d7bc08d58d2ec924d7fbb521-classes.dex", dex file "/data/data/sevrain.test/files/instant-run/dex/slice-com.android.support-appcompat-v7-23.3.0_02f1a8f82ff0c034bf1ca6149868d85ee2aa885e-classes.dex", dex file "/data/data/sevrain.test/files/instant-run/dex/slice-com.android.support-animated-vector-drawable-23.3.0_3fd5e9b04805488b8abc2dd11d113f60580edf7d-classes.dex"],nativeLibraryDirectories=[/data/app/sevrain.test-1/lib/x86, /vendor/lib, /system/lib]]
                                                                at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                at com.android.tools.fd.runtime.IncrementalClassLoader$DelegateClassLoader.findClass(IncrementalClassLoader.java:90)
                                                                at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                                at sevrain.test.Reglages.concatenateByteArray(Reglages.java:142) 
                                                                at sevrain.test.MainActivity$4.onClick(MainActivity.java:123) 
                                                                at android.view.View.performClick(View.java:5198) 
                                                                at android.view.View$PerformClick.run(View.java:21147) 
                                                                at android.os.Handler.handleCallback(Handler.java:739) 
                                                                at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                at android.os.Looper.loop(Looper.java:148) 
                                                                at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                at java.lang.reflect.Method.invoke(Native Method) 
                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                                            	Suppressed: java.lang.ClassNotFoundException: Didn't find class "org.joou.UByte" on path: DexPathList[[zip file "/data/app/sevrain.test-1/base.apk"],nativeLibraryDirectories=[/data/app/sevrain.test-1/lib/x86, /vendor/lib, /system/lib]]
                                                                at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                                		... 12 more
                                                            		Suppressed: java.lang.ClassNotFoundException: Didn't find class "org.joou.UByte" on path: DexPathList[[dex file "/data/data/sevrain.test/files/instant-run/dex/slice-support-annotations-23.3.0_5d2ef72a253a42531cccf688b31bc628a56ee084-classes.dex", dex file "/data/data/sevrain.test/files/instant-run/dex/slice-slice_9-classes.dex", dex file "/data/data/sevrain.test/files/instant-run/dex/slice-slice_8-classes.dex", dex file "/data/data/sevrain.test/files/instant-run/dex/slice-slice_7-classes.dex", dex file "/data/data/sevrain.test/files/instant-run

I added the library using "Library dependencies" and i searched for jOOU, it added the following line into my gradle file :

compile 'org.jooq:joou:0.9.1'

**Comment by lukaseder** [comment]
A `NoClassDefFoundError` usually happens when a dependency is correctly configured for compilation, but not for the runtime. I'm not acquainted with how gradle works, but it does look as though the jOOU library was not really deployed with your application.
